Update debug_client_main.cpp
Neboer/NerMCManager pull request #4
Opened 2024-07-16 04:23 UTC by lost0427

已实现指令
nmm ep list
nmm ep create <path>
nmm ep delete -t \<tag:version>
nmm ep rename -t \<tag:version> \<tag:version>
自动生成对应的JSON传给后端

2024-07-16 08:40 UTC, Neboer requested changes
首先，非常感谢你的提交，其次，这次提交有一些问题，已经在review里指出来了，希望你改正。

再次提醒，这个debug_client_main.cpp是用来客户端向服务器测试用的，不需要再继续开发和修改，你做的这些命令行解析的工作，应该属于正常的main文件完成的工作，不需要在debug_client_main.cpp中实现。请你将debug_client_main.cpp文件还原，然后在main.cpp中完成命令行解析和发包等功能。

如果有任何问题欢迎随时和我联系，拖了一天才来review你的pr真的非常抱歉。加油！

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
>  #include <iostream>
首先，非常感谢你的提交，其次，这次提交有一些问题，我会在review里指出，希望你可以尽快理解C++代码的编写方式和规范。

需要写在前面的是，这个debug_client_main.cpp是用来客户端向服务器测试用的，不需要再继续开发和修改，你做的这些命令行解析的工作，应该属于正常的main文件完成的工作，不需要在debug_client_main.cpp中实现。请你将debug_client_main.cpp文件还原，然后在main.cpp中完成命令行解析和发包等功能。

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +void splitByColon(const std::string& input, std::string& left, std::string& right) {
这里的设计有一点变化，经过考虑，我还是决定使用"-"做连接符号。更新之后的 docs/nermcmanager.md 已经提交到main分支，请你检查。这次更新主要是修改了一些命令的用法，取消了冒号分隔的设计。你可以对比一下新版文档和旧版的区别，再做打算。

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +nlohmann::json cli(const std::string& p1, const std::string& p2, const std::string& p3, const std::string& p4, const std::string& tag, const std::string& version, const std::string& new_tag, const st
nlohmann::json一律用using统一写成json。看我代码里尽量保持一致的简单写法：用str表示字符串，用json表示JSON对象，用fs来表示文件系统变量。
```c++
using str = std::string;
using json = nlohmann::json;
namespace fs = std::filesystem;
```

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +            jsonData["type"] = "get_env_packs";
缩进呢？缩进被你吃了（
VSCode可以自动format代码的，你打开命令菜单，敲format ，然后点format document，然后选用C/C++插件format，缩进调成4，就可以保证和我代码缩进风格一样了。

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +    if (argc < 3) {
不要手动解析args，我们有p-ranav/argparse

2024-07-16 08:40 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +nlohmann::json cli(const std::string& p1, const std::string& p2, const std::string& p3, const std::string& p4, const std::string& tag, const std::string& version, const std::string& new_tag, const st
在所有地方都要这么写，前后端都要保持一致的代码风格。

2024-07-16 10:19 UTC, lost0427 commented
已修改，感谢neboer指导
指令
nmm ep list
nmm ep create
nmm ep delete name-version
nmm ep rename  name-version  name-version
使用-t似乎会让分割-左右失败？不知道如何解决

2024-07-17 11:13 UTC, lost0427 commented
已修改

2024-07-17 23:47 UTC, Neboer commented on src/cli/debug_client_main.cpp
> +}
下次提交之前，注意不要污染自己没有修改的文件。在这里你把本来的换行给删了，这是不对的，文件结尾应该是一个换行。

2024-07-17 23:52 UTC, Neboer commented on src/cli/main.cpp
>  }
同样，文件结尾需要换行。

2024-07-18 00:02 UTC, Neboer approved these changes

2024-07-18 00:04 UTC, merged